#version: '3.7'

services:
  db:
    image: postgres:12
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - webnet

  web:
    build: .
    environment:
      - RUN_TESTS=0
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env  # Use an environment file for secrets
    volumes:
      - .:/app
    networks:
      - webnet

  test:
    build: .
    environment:
      - RUN_TESTS=1
      - PYTHONPATH=/app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - webnet

volumes:
  pgdata:

networks:
  webnet:
