from .typology_temporistics import TypologyTemporistics
from .typology_psychosophia import TypologyPsychosophia
from .typology_amatoric import TypologyAmatoric
from .typology_socionics import TypologySocionics
