"""Add user types

Revision ID: 412f969c6300
Revises: 5c36f679efe4
Create Date: 2024-09-14 14:45:53.683709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412f969c6300'
down_revision = '5c36f679efe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typology_name', sa.String(length=64), nullable=False),
    sa.Column('type_value', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_type')
    # ### end Alembic commands ###
